### ISSUE TITLE
ssh: handshake failed: ssh error

### ISSUE THREAD

**Issue by jinhao94** [mritd/mmh#28]
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

**My default.yaml**
```yaml
basic:
  password: ""
  port: 22
  private_key: /home/jinh/.ssh/id_rsa
  private_key_password: ""
  proxy: pbserver
  user: jinh
max_proxy: 5

servers:
- name: imau
  address: 172.25.4.21
  tags: ["imau"]

- name: node3
  address: 20.1.1.13
  user: jinh
  private_key: /home/jinh/.ssh/id_rsa
  tags: ["node3"]
  proxy: pbserver

- name: node4
  address: 20.1.1.14
  tags: ["node4"]
  private_key: /home/jinh/.ssh/id_rsa

- name: pbserver
  address: 20.1.1.10
  tags: ["pbserver"]
  private_key: /home/jinh/.ssh/id_rsa
```
Thank you in advance.
