### ISSUE TITLE
[Feature]添加公共配置项

### ISSUE THREAD

**Issue by bwangelme** [mritd/mmh#4]
## 相关背景

刚刚使用了一下这个工具，发现非常好用。

但是。。

我在设置配置文件的时候，感觉设置 `privatekey`, `privatekey_password` 这些配置项很麻烦，因为我的私钥基本上使用的都是同一个。一个相同的配置要加4 5 遍，以后如果要改也麻烦。

## 具体实现

所以请问是否考虑在配置文件中添加一个公共配置项，例如下面这样的:

```yaml
maxproxy: 5
basic:
- privatekey: ""
- privatekey_password: ""
servers:
- name:xxx
  tags:
  - test
  user: addxxx
  password: ""
  privatekey: /Users/michaeltsui/.ssh/id_rsa
  privatekey_password: ""
  address: xxx
  port: 22
  proxy: ""
- name: balrog2
  tags:
  - test
  user: xxx
  password: ""
  privatekey: /Users/michaeltsui/.ssh/id_rsa
  privatekey_password: ""
  address: addxxx
  port: 22
  proxy: ""
tags:
- test
```

`server`的每个配置项都可以在basic中配置，系统查找配置的时候，优先查`server`中对应 `name` 的，如果查不到再去查`basic`的。

## 愿意贡献力量

如果 repo 主觉得这个feature可以接受的话，我就准备看一下代码，看能不能自己实现了提一个PR过来。
